# api.yaml
openapi: 3.0.0
info:
  title: api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /posts/:
    get:
      summary: Posts Endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
      operationId: get-posts
      parameters:
        - schema:
            type: integer
          in: query
          name: id
        - schema:
            type: string
          in: query
          name: title
        - schema:
            type: string
          in: query
          name: location
        - schema:
            type: string
          in: query
          name: category
        - schema:
            type: string
          in: query
          name: tag
        - schema:
            type: string
          in: query
          name: subtag
        - schema:
            type: string
          in: query
          name: keyword
  /tags:
    get:
      summary: Tags Endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  getAllTags:
                    type: boolean
                  tags:
                    type: array
                    items:
                      type: object
                      properties:
                        thisTag:
                          type: string
                        subTags:
                          type: array
                          items:
                            type: string
              examples: {}
      operationId: get-tags
      description: Obtain a full list of tags or a queried subset of tags
  /categories:
    get:
      summary: Categories Endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      type: string
      operationId: get-categories
      description: Obtain a list of categories
components:
  schemas: {}