# Generated by Django 3.1.2 on 2020-11-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='subtag',
        ),
        migrations.AddField(
            model_name='tag',
            name='keywords',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subtag',
        ),
    ]
