# Generated by Django 3.1.5 on 2021-01-06 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210106_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='keywords',
        ),
    ]
