# Generated by Django 3.1.5 on 2021-01-06 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
