# Generated by Django 3.1.5 on 2021-01-06 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210106_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='img_path',
        ),
    ]
