# Generated by Django 3.1.5 on 2021-01-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0012_auto_20210111_0055'), ('api', '0013_auto_20210111_0127'), ('api', '0014_auto_20210111_0235'), ('api', '0015_auto_20210111_0238'), ('api', '0016_auto_20210111_0301'), ('api', '0017_auto_20210111_0421')]

    dependencies = [
        ('api', '0011_auto_20210106_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_path',
            new_name='img_file',
        ),
        migrations.AddField(
            model_name='image',
            name='img_name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
