# Generated by Django 3.1.5 on 2021-01-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210111_0055_squashed_0017_auto_20210111_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('SP', 'Spanish')], default='EN', max_length=20),
        ),
    ]
