# Generated by Django 3.2 on 2021-05-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210126_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_post_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
