# Generated by Django 3.1.7 on 2021-05-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_image_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
