# Generated by Django 3.2 on 2021-05-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_image_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='posts', to='api.Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='posts', to='api.Location'),
        ),
    ]
