# Generated by Django 3.2 on 2021-05-03 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_pdf'),
        ('api', '0020_auto_20210502_1408'),
    ]

    operations = [
    ]
