# Generated by Django 3.2 on 2021-05-03 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_0018_pdf_0020_auto_20210502_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pdf'),
        ),
    ]
