# Generated by Django 3.1.7 on 2021-05-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_post_featured_post_order'),
        ('api', '0022_post_pdf'),
        ('api', '0020_post_region'),
    ]

    operations = [
    ]
