# Generated by Django 3.1.7 on 2021-05-27 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210527_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.region'),
        ),
    ]
